/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Vista.Clientes.cn;
import static Vista.Clientes.rs;
import static Vista.Clientes.s;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import com.itextpdf.text.Font;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.FontFactory;
import java.util.Properties;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.EmailAttachment;
import org.apache.commons.mail.MultiPartEmail;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;
import javax.mail.util.ByteArrayDataSource;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.Transport;
import org.apache.commons.mail.EmailAttachment;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.MultiPartEmail;
import org.apache.commons.mail.DefaultAuthenticator;
import javax.mail.Authenticator;
import javax.mail.PasswordAuthentication;


/**
 *
 * @author catal
 */
public class Transporte extends javax.swing.JFrame {

    /**
     * Creates new form Transporte
     */
    public Transporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSeleccionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLugar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldVehiculo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldConductor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVueltaLugar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldVueltaHora = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldVueltaVehiculo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldVueltaConductor = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonGenerar = new javax.swing.JButton();
        jButtonEnviar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMenuAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButtonVer.setText("Ver Reservas de Transportes");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });

        jLabel3.setText("LLENAR DATOS DE TRANSPORTE");

        jLabel4.setText("Lugar de encuentro:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("IDA - Domicilio a Departamento");

        jTextFieldLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLugarActionPerformed(evt);
            }
        });

        jLabel6.setText("Hora de encuentro:");

        jTextFieldHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraActionPerformed(evt);
            }
        });

        jLabel7.setText("Vehículo y patente:");

        jTextFieldVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVehiculoActionPerformed(evt);
            }
        });

        jLabel8.setText("Conductor a cargo:");

        jTextFieldConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConductorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("VUELTA - Departamento a Domicilio");

        jLabel10.setText("Lugar de encuentro:");

        jTextFieldVueltaLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVueltaLugarActionPerformed(evt);
            }
        });

        jLabel11.setText("Hora de encuentro:");

        jTextFieldVueltaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVueltaHoraActionPerformed(evt);
            }
        });

        jLabel12.setText("Vehículo y patente:");

        jTextFieldVueltaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVueltaVehiculoActionPerformed(evt);
            }
        });

        jLabel13.setText("Conductor a cargo:");

        jTextFieldVueltaConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVueltaConductorActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar datos");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonGenerar.setText("Generar Documento");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jButtonEnviar.setText("ENVIAR DOCUMENTO A CLIENTE ASOCIADO");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldVueltaLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel13))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldVueltaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldVueltaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldVueltaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jButtonEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jButtonVer)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonSeleccionar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSeleccionar)
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldVueltaLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldVueltaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldVueltaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldVueltaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerar)
                    .addComponent(jButtonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Planificación de Transporte");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/transportelogo.png"))); // NOI18N

        btnMenuAdmin.setText("Menú Administración");
        btnMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnMenuAdmin)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenuAdmin)
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAdminActionPerformed
        Admin sis = new Admin();
        sis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuAdminActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        // TODO add your handling code here:
                try {
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@localhost:1521/XE";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio", "duoc");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
             rs = s.executeQuery("select * from DATOS_TRANSPORTE");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las columnas
            for (int i = 1; i <= cantidadColumnas; i++) {
             modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rs.next()) {
             Object[] fila = new Object[cantidadColumnas];
             for (int i = 0; i < cantidadColumnas; i++) {
               fila[i]=rs.getObject(i+1);
             }
             modelo.addRow(fila);
            }
            rs.close();
            cn.close();
       } catch (Exception ex) {
        ex.printStackTrace();
       }
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jTextFieldLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLugarActionPerformed
        // TODO add your handling code here:
        jTextFieldLugar.getText();
    }//GEN-LAST:event_jTextFieldLugarActionPerformed

    private void jTextFieldHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraActionPerformed
        // TODO add your handling code here:
        jTextFieldHora.getText();
    }//GEN-LAST:event_jTextFieldHoraActionPerformed

    private void jTextFieldVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVehiculoActionPerformed
        // TODO add your handling code here:
        jTextFieldVehiculo.getText();
    }//GEN-LAST:event_jTextFieldVehiculoActionPerformed

    private void jTextFieldConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConductorActionPerformed
        // TODO add your handling code here:
        jTextFieldConductor.getText();
    }//GEN-LAST:event_jTextFieldConductorActionPerformed

    private void jTextFieldVueltaLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVueltaLugarActionPerformed
        // TODO add your handling code here:
        jTextFieldVueltaLugar.getText();
    }//GEN-LAST:event_jTextFieldVueltaLugarActionPerformed

    private void jTextFieldVueltaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVueltaHoraActionPerformed
        // TODO add your handling code here:
        jTextFieldVueltaHora.getText();
    }//GEN-LAST:event_jTextFieldVueltaHoraActionPerformed

    private void jTextFieldVueltaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVueltaVehiculoActionPerformed
        // TODO add your handling code here:
        jTextFieldVueltaVehiculo.getText();
    }//GEN-LAST:event_jTextFieldVueltaVehiculoActionPerformed

    private void jTextFieldVueltaConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVueltaConductorActionPerformed
        // TODO add your handling code here:
        jTextFieldVueltaConductor.getText();
    }//GEN-LAST:event_jTextFieldVueltaConductorActionPerformed

    
public class MyAuthenticator extends Authenticator {
    private String usuario;
    private String contraseña;

    public MyAuthenticator(String usuario, String contraseña) {
        this.usuario = usuario;
        this.contraseña = contraseña;
    }

    @Override
    protected PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication(usuario, contraseña);
    }
}    
    
    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
try {
    String correoEmisor = "jor.fernandezj@duocuc.cl";
    String contraseña = "F19485997-K";
    String destino = "koke.fernandez02@gmail.com";
    String asunto = "Prueba portafolio";
    String mensaje = "Muy buenos días Estimado,\n\n" +
            "Espero que se encuentre bien. Adjunto a este correo encontrarás el documento de 'Coordinación de Transporte' que solicitaste.\n\n" +
            "Por favor, revisa el documento y no dudes en ponerte en contacto si tienes alguna pregunta o necesitas información adicional. Estamos a tu disposición para ayudarte en todo lo que necesites.\n\n" +
            "Gracias por confiar en nuestros servicios y que tengas un excelente día.\n\n" +
            "Atentamente,\n" +
            "[Tu Nombre]";
    String archivoAdjunto = "C:\\Users\\flame\\Downloads\\DatosTransporte.pdf"; // Reemplaza con la ruta de tu archivo PDF

    // Configura las propiedades SMTP
    Properties properties = new Properties();
    properties.put("mail.smtp.host", "smtp.office365.com");
    properties.put("mail.smtp.port", "587");
    properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
    properties.put("mail.smtp.auth", "true");
    properties.put("mail.smtp.starttls.enable", "true"); 
    // Crea una nueva sesión con un autenticador
    Session session = Session.getInstance(properties, new Authenticator() {
        public PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(correoEmisor, contraseña);
        }
    });

    // Crea un objeto MimeMessage
    MimeMessage mimeMessage = new MimeMessage(session);
    mimeMessage.setFrom(new InternetAddress(correoEmisor));
    mimeMessage.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destino));
    mimeMessage.setSubject(asunto);

    // Crea el cuerpo del mensaje
    MimeBodyPart messageBodyPart = new MimeBodyPart();
    messageBodyPart.setText(mensaje);

    // Crea el archivo adjunto
    MimeBodyPart attachmentPart = new MimeBodyPart();
    FileDataSource fileDataSource = new FileDataSource(archivoAdjunto);
    attachmentPart.setDataHandler(new DataHandler(fileDataSource));
    attachmentPart.setFileName(fileDataSource.getName());

    // Crea un Multipart para el mensaje
    Multipart multipart = new MimeMultipart();
    multipart.addBodyPart(messageBodyPart);
    multipart.addBodyPart(attachmentPart);

    mimeMessage.setContent(multipart);

    // Envía el correo
    Transport.send(mimeMessage);

    System.out.println("Correo enviado con éxito");
} catch (MessagingException e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
                       
            Connection conn = null;
            PreparedStatement pstmt = null;

            try {
                //string conexion
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Portafolio", "duoc");
                String consultaSQL = "INSERT INTO DATOS_TRANSPORTE (lugar_encuentro_ida,hora_encuentro_ida,vehiculo_encuentro_ida,conductor_encuentro_ida,lugar_encuentro_vuelta,hora_encuentro_vuelta,vehiculo_encuentro_vuelta,conductor_encuentro_vuelta) VALUES (?,?,?,?,?,?,?,?)";
                // Crea una declaración preparada
                PreparedStatement preparedStatement = conn.prepareStatement(consultaSQL);

                // Establece el valor que deseas guardar en la base de datos
                preparedStatement.setString(1, jTextFieldLugar.getText());
                preparedStatement.setString(2, jTextFieldHora.getText());
                preparedStatement.setString(3, jTextFieldVehiculo.getText());
                preparedStatement.setString(4, jTextFieldConductor.getText());
                preparedStatement.setString(5, jTextFieldVueltaLugar.getText());
                preparedStatement.setString(6, jTextFieldVueltaHora.getText());
                preparedStatement.setString(7, jTextFieldVueltaVehiculo.getText());
                preparedStatement.setString(8, jTextFieldVueltaConductor.getText());
                //Ejecuta la consulta
                preparedStatement.executeUpdate();
 JOptionPane.showMessageDialog(this, "ingreso exitoso");
                // Cierra la conexión y la declaración
                preparedStatement.close();
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
                // Maneja la excepción de manera apropiada
            }
     
    
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        // TODO add your handling code here:
                    Connection conn = null;
            PreparedStatement pstmt = null;
            
            try {
        // Configura la conexión a la base de datos Oracle
                conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Portafolio", "duoc");
                String consultaSQL = "SELECT * from datos_transporte";

        // Prepara una consulta SQL para obtener los datos de la tabla
        String sql = "SELECT * FROM datos_transporte";
        PreparedStatement stmt = conn.prepareStatement(sql);
        
        // Ejecuta la consulta y obtiene los resultados
        ResultSet resultSet = stmt.executeQuery();
        
        // Crear un documento PDF
        Document documento = new Document();
        
        // Nombre del archivo PDF resultante
        String nombreArchivo = "C:\\Users\\flame\\Downloads\\DatosTransporte.pdf";
        
        // Crear el archivo PDF
        PdfWriter.getInstance(documento, new FileOutputStream(nombreArchivo));
        
        // Abre el documento para comenzar a escribir
        documento.open();
        
        // Aquí puedes personalizar el contenido del PDF
        // Por ejemplo, puedes recorrer los resultados de la consulta y agregarlos al PDF
        while (resultSet.next()) {
            String lugar1 = resultSet.getString("lugar_encuentro_ida");
            String hora1 = resultSet.getString("hora_encuentro_ida");
            String vehiculo1 = resultSet.getString("vehiculo_encuentro_ida");
            String conductor1 = resultSet.getString("conductor_encuentro_ida");
            String lugarvuelta = resultSet.getString("lugar_encuentro_vuelta");
            String horavuelta = resultSet.getString("hora_encuentro_vuelta");
            String vehiculovuelta = resultSet.getString("vehiculo_encuentro_vuelta");
            String conductorvuelta = resultSet.getString("conductor_encuentro_vuelta");
            
            // Agregar los datos al PDF
            Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
Chunk titulo = new Chunk("Datos de su Transporte", tituloFont);
            documento.add(new Paragraph(titulo));
            documento.add(new Paragraph(" " ));
            documento.add(new Paragraph("lugar de encuentro de ida: " + lugar1));
            documento.add(new Paragraph("hora de encuentro de ida: " + hora1));
            documento.add(new Paragraph("vehiculo de encuentro de ida: " + vehiculo1));
            documento.add(new Paragraph("conductor de encuentro de ida: " + conductor1));
            documento.add(new Paragraph("lugar de encuentro de vuelta: " + lugarvuelta));
            documento.add(new Paragraph("hora de encuentro de vuelta: " + horavuelta));
            documento.add(new Paragraph("vehiculo de encuentro de vuelta: " + vehiculovuelta));
            documento.add(new Paragraph("conductor de encuentro de vuelta: " + conductorvuelta));
            documento.add(new Paragraph(" " ));
            documento.add(new Paragraph(" Recuerde por su seguridad ningun conductor le pedira sus datos personales " ));
            documento.add(new Paragraph("Portafolio Version de Prueba " ));
            documento.add(new Paragraph("\n")); // Agregar un salto de línea
        }
        
        // Cierra el documento
        documento.close();
        
        // Cierra la conexión y libera recursos
        conn.close();
        
        System.out.println("Archivo PDF creado con éxito.");
        System.out.println("Ruta del archivo PDF: " + nombreArchivo);
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuAdmin;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldConductor;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldVehiculo;
    private javax.swing.JTextField jTextFieldVueltaConductor;
    private javax.swing.JTextField jTextFieldVueltaHora;
    private javax.swing.JTextField jTextFieldVueltaLugar;
    private javax.swing.JTextField jTextFieldVueltaVehiculo;
    // End of variables declaration//GEN-END:variables
}
